package lk.ac.sliit.ridelink.driver.application.usecase;
import lk.ac.sliit.ridelink.driver.application.dto.request.*; import lk.ac.sliit.ridelink.driver.application.port.out.AccountValidationPort; import lk.ac.sliit.ridelink.driver.domain.enums.*; import lk.ac.sliit.ridelink.driver.domain.exception.*; import lk.ac.sliit.ridelink.driver.domain.model.*; import lk.ac.sliit.ridelink.driver.domain.repository.*; import lk.ac.sliit.ridelink.driver.infrastructure.client.DownstreamServiceException;
import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension; import java.math.BigDecimal; import java.time.Instant; import java.util.*; import static org.assertj.core.api.Assertions.*; import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class) class DriverVehicleApplicationServiceTest {
 @Mock DriverProfileRepository drivers; @Mock VehicleRepository vehicles; @Mock AccountValidationPort accounts; DriverVehicleApplicationService service;
 @BeforeEach void setup(){service=new DriverVehicleApplicationService(drivers,vehicles,accounts);}
 @Test void createsValidDriverProfile(){UUID account=UUID.randomUUID();when(accounts.isActiveDriver(account)).thenReturn(true);when(drivers.save(any())).thenAnswer(i->i.getArgument(0));var r=service.createProfile(account,new CreateDriverProfileRequest(" b 123 ","Colombo"));assertThat(r.accountId()).isEqualTo(account);assertThat(r.licenceNumber()).isEqualTo("B123");assertThat(r.availabilityStatus()).isEqualTo(AvailabilityStatus.OFFLINE);}
 @Test void rejectsInvalidAccount(){when(accounts.isActiveDriver(any())).thenReturn(false);assertThatThrownBy(()->service.createProfile(UUID.randomUUID(),new CreateDriverProfileRequest("L1","Colombo"))).isInstanceOf(InvalidDriverAccountException.class);}
 @Test void rejectsDuplicateLicence(){when(accounts.isActiveDriver(any())).thenReturn(true);when(drivers.existsByLicenceNumber("L1")).thenReturn(true);assertThatThrownBy(()->service.createProfile(UUID.randomUUID(),new CreateDriverProfileRequest("L1","Colombo"))).isInstanceOf(DuplicateLicenceException.class);}
 @Test void registersVehicleAndRejectsDuplicate(){DriverProfile d=driver(AvailabilityStatus.OFFLINE);when(drivers.findByAccountId(d.getAccountId())).thenReturn(Optional.of(d));when(vehicles.save(any())).thenAnswer(i->i.getArgument(0));var req=new RegisterVehicleRequest("WP CAR 1","Toyota","Aqua","Blue",VehicleType.CAR,2020);assertThat(service.registerVehicle(d.getAccountId(),req).registrationNumber()).isEqualTo("WPCAR1");when(vehicles.existsByRegistrationNumber("WPCAR1")).thenReturn(true);assertThatThrownBy(()->service.registerVehicle(d.getAccountId(),req)).isInstanceOf(DuplicateRegistrationException.class);}
 @Test void updatesVehicleOwnedByDriver(){DriverProfile d=driver(AvailabilityStatus.OFFLINE);Vehicle v=vehicle(d.getId(),VehicleType.CAR,true);when(vehicles.findById(v.getId())).thenReturn(Optional.of(v));when(drivers.findById(d.getId())).thenReturn(Optional.of(d));when(vehicles.save(any())).thenAnswer(i->i.getArgument(0));var r=service.updateVehicle(d.getAccountId(),false,v.getId(),new UpdateVehicleRequest("Honda","Fit","White",VehicleType.CAR,2022));assertThat(r.make()).isEqualTo("Honda");assertThat(r.manufacturingYear()).isEqualTo(2022);}
 @Test void cannotBecomeAvailableWithoutVehicle(){DriverProfile d=driver(AvailabilityStatus.OFFLINE);when(drivers.findByAccountId(d.getAccountId())).thenReturn(Optional.of(d));assertThatThrownBy(()->service.updateAvailability(d.getAccountId(),AvailabilityStatus.AVAILABLE)).isInstanceOf(InvalidAvailabilityTransitionException.class);}
 @Test void becomesAvailableWithVehicle(){DriverProfile d=driver(AvailabilityStatus.OFFLINE);when(drivers.findByAccountId(d.getAccountId())).thenReturn(Optional.of(d));when(vehicles.existsActiveByDriverId(d.getId())).thenReturn(true);when(drivers.save(any())).thenAnswer(i->i.getArgument(0));assertThat(service.updateAvailability(d.getAccountId(),AvailabilityStatus.AVAILABLE).availabilityStatus()).isEqualTo(AvailabilityStatus.AVAILABLE);}
 @Test void validatesCoordinateBoundaries(){DriverProfile d=driver(AvailabilityStatus.OFFLINE);when(drivers.findByAccountId(d.getAccountId())).thenReturn(Optional.of(d));when(drivers.save(any())).thenAnswer(i->i.getArgument(0));assertThat(service.updateLocation(d.getAccountId(),new LocationRequest(BigDecimal.valueOf(90),BigDecimal.valueOf(-180))).currentLatitude()).isEqualByComparingTo("90");assertThatThrownBy(()->d.updateLocation(BigDecimal.valueOf(91),BigDecimal.ZERO)).isInstanceOf(IllegalArgumentException.class);}
 @Test void filtersAndMapsEligibleDriver(){DriverProfile d=driver(AvailabilityStatus.AVAILABLE);Vehicle v=vehicle(d.getId(),VehicleType.CAR,true);when(drivers.findEligible("colombo",VehicleType.CAR)).thenReturn(List.of(d));when(vehicles.findFirstActiveMatching(d.getId(),VehicleType.CAR)).thenReturn(Optional.of(v));assertThat(service.findEligible(" Colombo ",VehicleType.CAR)).singleElement().extracting(x->x.vehicleId()).isEqualTo(v.getId());}
 @Test void excludesDriverWhenVehicleTypeDoesNotMatch(){DriverProfile d=driver(AvailabilityStatus.AVAILABLE);when(drivers.findEligible("colombo",VehicleType.VAN)).thenReturn(List.of(d));when(vehicles.findFirstActiveMatching(d.getId(),VehicleType.VAN)).thenReturn(Optional.empty());assertThat(service.findEligible("Colombo",VehicleType.VAN)).isEmpty();}
 @Test void excludesDriversOutsideRequestedServiceArea(){when(drivers.findEligible("galle",VehicleType.CAR)).thenReturn(List.of());assertThat(service.findEligible(" Galle ",VehicleType.CAR)).isEmpty();verify(drivers).findEligible("galle",VehicleType.CAR);}
 @Test void propagatesDownstreamAccountServiceFailure(){when(accounts.isActiveDriver(any())).thenThrow(new DownstreamServiceException("Account Service unavailable"));assertThatThrownBy(()->service.createProfile(UUID.randomUUID(),new CreateDriverProfileRequest("L1","Colombo"))).isInstanceOf(DownstreamServiceException.class);}
 @Test void marksOnRideAndRestoresMatchingRide(){DriverProfile d=driver(AvailabilityStatus.AVAILABLE);UUID ride=UUID.randomUUID();when(drivers.findById(d.getId())).thenReturn(Optional.of(d));when(vehicles.existsActiveByDriverId(d.getId())).thenReturn(true);when(drivers.save(any())).thenAnswer(i->i.getArgument(0));assertThat(service.assign(d.getId(),ride).availabilityStatus()).isEqualTo(AvailabilityStatus.ON_RIDE);assertThat(service.restore(d.getId(),ride).availabilityStatus()).isEqualTo(AvailabilityStatus.AVAILABLE);}
 @Test void rejectsWrongRideRestoration(){DriverProfile d=driver(AvailabilityStatus.AVAILABLE);UUID ride=UUID.randomUUID();d.assign(ride);when(drivers.findById(d.getId())).thenReturn(Optional.of(d));assertThatThrownBy(()->service.restore(d.getId(),UUID.randomUUID())).isInstanceOf(InvalidAvailabilityTransitionException.class);}
 @Test void preventsAnotherDriverUpdatingVehicle(){DriverProfile owner=driver(AvailabilityStatus.OFFLINE);Vehicle v=vehicle(owner.getId(),VehicleType.CAR,true);when(vehicles.findById(v.getId())).thenReturn(Optional.of(v));when(drivers.findById(owner.getId())).thenReturn(Optional.of(owner));assertThatThrownBy(()->service.updateVehicle(UUID.randomUUID(),false,v.getId(),new UpdateVehicleRequest("T","M","B",VehicleType.CAR,2020))).isInstanceOf(ForbiddenOperationException.class);}
 private DriverProfile driver(AvailabilityStatus s){Instant now=Instant.now();return new DriverProfile(UUID.randomUUID(),UUID.randomUUID(),"L1",s,"Colombo",BigDecimal.ONE,BigDecimal.ONE,s==AvailabilityStatus.AVAILABLE?now:null,null,now,now);}
 private Vehicle vehicle(UUID driver,VehicleType type,boolean active){Instant now=Instant.now();return new Vehicle(UUID.randomUUID(),driver,"REG1","Make","Model","Blue",type,2020,active,now,now);}
}
