package lk.ac.sliit.ridelink.ride.presentation.exception;
import jakarta.servlet.http.HttpServletRequest; import lk.ac.sliit.ridelink.ride.application.usecase.ExternalServiceException; import lk.ac.sliit.ridelink.ride.domain.exception.*; import org.springframework.dao.*; import org.springframework.http.*; import org.springframework.http.converter.HttpMessageNotReadableException; import org.springframework.orm.ObjectOptimisticLockingFailureException; import org.springframework.security.access.AccessDeniedException; import org.springframework.security.authorization.AuthorizationDeniedException; import org.springframework.web.bind.*; import org.springframework.web.bind.annotation.*; import org.springframework.web.method.annotation.MethodArgumentTypeMismatchException; import java.time.Instant; import java.util.*;
@RestControllerAdvice public class GlobalExceptionHandler {
 @ExceptionHandler(MethodArgumentNotValidException.class) ResponseEntity<ApiErrorResponse> validation(MethodArgumentNotValidException e,HttpServletRequest r){return out(HttpStatus.BAD_REQUEST,"Request validation failed",r,e.getBindingResult().getFieldErrors().stream().map(x->new ValidationError(x.getField(),x.getDefaultMessage())).toList());}
 @ExceptionHandler({MethodArgumentTypeMismatchException.class,HttpMessageNotReadableException.class,IllegalArgumentException.class}) ResponseEntity<ApiErrorResponse> bad(Exception e,HttpServletRequest r){return out(HttpStatus.BAD_REQUEST,e.getMessage()==null?"Invalid request value":e.getMessage(),r,List.of());}
 @ExceptionHandler(RideNotFoundException.class) ResponseEntity<ApiErrorResponse> missing(Exception e,HttpServletRequest r){return out(HttpStatus.NOT_FOUND,e.getMessage(),r,List.of());}
 @ExceptionHandler({ForbiddenRideOperationException.class,AccessDeniedException.class,AuthorizationDeniedException.class}) ResponseEntity<ApiErrorResponse> forbidden(Exception e,HttpServletRequest r){return out(HttpStatus.FORBIDDEN,"You do not have permission to perform this operation",r,List.of());}
 @ExceptionHandler(PassengerValidationException.class) ResponseEntity<ApiErrorResponse> passenger(Exception e,HttpServletRequest r){return out(HttpStatus.UNPROCESSABLE_ENTITY,e.getMessage(),r,List.of());}
 @ExceptionHandler(NoAvailableDriverException.class) ResponseEntity<ApiErrorResponse> unavailableDriver(Exception e,HttpServletRequest r){return out(HttpStatus.SERVICE_UNAVAILABLE,e.getMessage(),r,List.of());}
 @ExceptionHandler({InvalidRideTransitionException.class,ObjectOptimisticLockingFailureException.class,DataIntegrityViolationException.class}) ResponseEntity<ApiErrorResponse> conflict(Exception e,HttpServletRequest r){return out(HttpStatus.CONFLICT,e.getMessage(),r,List.of());}
 @ExceptionHandler(ExternalServiceException.class) ResponseEntity<ApiErrorResponse> downstream(ExternalServiceException e,HttpServletRequest r){return out(e.isTimeout()?HttpStatus.GATEWAY_TIMEOUT:HttpStatus.SERVICE_UNAVAILABLE,e.getMessage(),r,List.of());}
 @ExceptionHandler(Exception.class) ResponseEntity<ApiErrorResponse> unexpected(Exception e,HttpServletRequest r){return out(HttpStatus.INTERNAL_SERVER_ERROR,"An unexpected server error occurred",r,List.of());}
 private ResponseEntity<ApiErrorResponse> out(HttpStatus s,String m,HttpServletRequest r,List<ValidationError> v){return ResponseEntity.status(s).body(new ApiErrorResponse(Instant.now(),s.value(),s.getReasonPhrase(),m,r.getRequestURI(),v));}
}
