package lk.ac.sliit.ridelink.ride.infrastructure.persistence.entity;
import jakarta.persistence.*; import lk.ac.sliit.ridelink.ride.domain.enums.*; import java.math.BigDecimal; import java.time.Instant; import java.util.UUID;
@Entity @Table(name="rides",indexes={@Index(name="idx_rides_passenger_requested",columnList="passenger_id,requested_at"),@Index(name="idx_rides_driver_requested",columnList="driver_id,requested_at"),@Index(name="idx_rides_status_requested",columnList="status,requested_at"),@Index(name="idx_rides_driver_sync",columnList="driver_sync_status")})
public class RideJpaEntity {
 @Id private UUID id; @Column(name="passenger_id",nullable=false) private UUID passengerId; @Column(name="driver_id") private UUID driverId; @Column(name="driver_profile_id") private UUID driverProfileId; @Column(name="vehicle_id") private UUID vehicleId;
 @Column(name="pickup_name",nullable=false,length=160) private String pickupName; @Column(name="destination_name",nullable=false,length=160) private String destinationName; @Column(name="service_area",nullable=false,length=80) private String serviceArea; @Column(name="simulated_distance_km",nullable=false,precision=10,scale=2) private BigDecimal simulatedDistanceKm;
 @Enumerated(EnumType.STRING) @Column(name="vehicle_type",nullable=false,length=16) private VehicleType vehicleType; @Column(name="estimated_fare",nullable=false,precision=12,scale=2) private BigDecimal estimatedFare; @Column(name="final_fare",precision=12,scale=2) private BigDecimal finalFare; @Enumerated(EnumType.STRING) @Column(nullable=false,length=20) private RideStatus status;
 @Column(name="requested_at",nullable=false) private Instant requestedAt; @Column(name="assigned_at") private Instant assignedAt; @Column(name="accepted_at") private Instant acceptedAt; @Column(name="started_at") private Instant startedAt; @Column(name="completed_at") private Instant completedAt; @Column(name="cancelled_at") private Instant cancelledAt; @Column(name="cancellation_reason",length=500) private String cancellationReason;
 @Enumerated(EnumType.STRING) @Column(name="driver_sync_status",nullable=false,length=24) private DriverSyncStatus driverSyncStatus; @Column(name="created_at",nullable=false) private Instant createdAt; @Column(name="updated_at",nullable=false) private Instant updatedAt; @Version private long version;
 public RideJpaEntity(){}
 public UUID getId(){return id;} public void setId(UUID v){id=v;} public UUID getPassengerId(){return passengerId;} public void setPassengerId(UUID v){passengerId=v;} public UUID getDriverId(){return driverId;} public void setDriverId(UUID v){driverId=v;} public UUID getDriverProfileId(){return driverProfileId;} public void setDriverProfileId(UUID v){driverProfileId=v;} public UUID getVehicleId(){return vehicleId;} public void setVehicleId(UUID v){vehicleId=v;} public String getPickupName(){return pickupName;} public void setPickupName(String v){pickupName=v;} public String getDestinationName(){return destinationName;} public void setDestinationName(String v){destinationName=v;} public String getServiceArea(){return serviceArea;} public void setServiceArea(String v){serviceArea=v;} public BigDecimal getSimulatedDistanceKm(){return simulatedDistanceKm;} public void setSimulatedDistanceKm(BigDecimal v){simulatedDistanceKm=v;} public VehicleType getVehicleType(){return vehicleType;} public void setVehicleType(VehicleType v){vehicleType=v;} public BigDecimal getEstimatedFare(){return estimatedFare;} public void setEstimatedFare(BigDecimal v){estimatedFare=v;} public BigDecimal getFinalFare(){return finalFare;} public void setFinalFare(BigDecimal v){finalFare=v;} public RideStatus getStatus(){return status;} public void setStatus(RideStatus v){status=v;} public Instant getRequestedAt(){return requestedAt;} public void setRequestedAt(Instant v){requestedAt=v;} public Instant getAssignedAt(){return assignedAt;} public void setAssignedAt(Instant v){assignedAt=v;} public Instant getAcceptedAt(){return acceptedAt;} public void setAcceptedAt(Instant v){acceptedAt=v;} public Instant getStartedAt(){return startedAt;} public void setStartedAt(Instant v){startedAt=v;} public Instant getCompletedAt(){return completedAt;} public void setCompletedAt(Instant v){completedAt=v;} public Instant getCancelledAt(){return cancelledAt;} public void setCancelledAt(Instant v){cancelledAt=v;} public String getCancellationReason(){return cancellationReason;} public void setCancellationReason(String v){cancellationReason=v;} public DriverSyncStatus getDriverSyncStatus(){return driverSyncStatus;} public void setDriverSyncStatus(DriverSyncStatus v){driverSyncStatus=v;} public Instant getCreatedAt(){return createdAt;} public void setCreatedAt(Instant v){createdAt=v;} public Instant getUpdatedAt(){return updatedAt;} public void setUpdatedAt(Instant v){updatedAt=v;} public long getVersion(){return version;} public void setVersion(long v){version=v;}
}
