package lk.ac.sliit.ridelink.driver.presentation;
import io.jsonwebtoken.Jwts; import io.jsonwebtoken.security.Keys; import lk.ac.sliit.ridelink.driver.application.port.out.AccountValidationPort; import org.junit.jupiter.api.Test; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.boot.test.mock.mockito.MockBean; import org.springframework.http.MediaType; import org.springframework.test.context.ActiveProfiles; import org.springframework.test.web.servlet.MockMvc; import java.nio.charset.StandardCharsets; import java.time.Instant; import java.util.*; import static org.mockito.Mockito.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("test") class DriverVehicleApiIntegrationTest {
 static final String SECRET="test-only-secret-at-least-thirty-two-characters-long"; @Autowired MockMvc mvc; @MockBean AccountValidationPort accounts;
 @Test void anonymousIsUnauthorized()throws Exception{mvc.perform(get("/api/v1/drivers/me")).andExpect(status().isUnauthorized());}
 @Test void passengerIsForbidden()throws Exception{mvc.perform(get("/api/v1/drivers/me").header("Authorization","Bearer "+token(UUID.randomUUID(),"PASSENGER","USER"))).andExpect(status().isForbidden());}
 @Test void driverCanCreateProfileAndValidationErrorsAreConsistent()throws Exception{UUID account=UUID.randomUUID();when(accounts.isActiveDriver(account)).thenReturn(true);String jwt=token(account,"DRIVER","USER");mvc.perform(post("/api/v1/drivers/me").header("Authorization","Bearer "+jwt).contentType(MediaType.APPLICATION_JSON).content("{\"licenceNumber\":\"B1234567\",\"serviceArea\":\"Colombo\"}")).andExpect(status().isCreated()).andExpect(jsonPath("$.accountId").value(account.toString())).andExpect(jsonPath("$.availabilityStatus").value("OFFLINE"));mvc.perform(put("/api/v1/drivers/me/location").header("Authorization","Bearer "+jwt).contentType(MediaType.APPLICATION_JSON).content("{\"latitude\":91,\"longitude\":0}")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.validationErrors").isArray());}
 private String token(UUID subject,String role,String type){Instant now=Instant.now();return Jwts.builder().subject(subject.toString()).issuer("ridelink-account-service").claim("role",role).claim("token_type",type).issuedAt(Date.from(now)).expiration(Date.from(now.plusSeconds(600))).signWith(Keys.hmacShaKeyFor(SECRET.getBytes(StandardCharsets.UTF_8))).compact();}
}
