package lk.ac.sliit.ridelink.driver.presentation.exception;
import jakarta.servlet.http.HttpServletRequest; import lk.ac.sliit.ridelink.driver.domain.exception.*; import lk.ac.sliit.ridelink.driver.infrastructure.client.DownstreamServiceException; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.http.*; import org.springframework.http.converter.HttpMessageNotReadableException; import org.springframework.web.bind.*; import org.springframework.web.bind.annotation.*; import org.springframework.web.method.annotation.MethodArgumentTypeMismatchException; import java.time.Instant; import java.util.*;
@RestControllerAdvice public class GlobalExceptionHandler {
 @ExceptionHandler(MethodArgumentNotValidException.class) ResponseEntity<ApiErrorResponse> validation(MethodArgumentNotValidException e,HttpServletRequest r){return out(HttpStatus.BAD_REQUEST,"Request validation failed",r,e.getBindingResult().getFieldErrors().stream().map(x->new ValidationError(x.getField(),x.getDefaultMessage())).toList());}
 @ExceptionHandler({MethodArgumentTypeMismatchException.class,HttpMessageNotReadableException.class,IllegalArgumentException.class}) ResponseEntity<ApiErrorResponse> bad(Exception e,HttpServletRequest r){return out(HttpStatus.BAD_REQUEST,e.getMessage()==null?"Invalid request value":e.getMessage(),r,List.of());}
 @ExceptionHandler({DuplicateLicenceException.class,DuplicateRegistrationException.class,InvalidAvailabilityTransitionException.class,IllegalStateException.class,DataIntegrityViolationException.class}) ResponseEntity<ApiErrorResponse> conflict(Exception e,HttpServletRequest r){return out(HttpStatus.CONFLICT,e.getMessage(),r,List.of());}
 @ExceptionHandler({DriverProfileNotFoundException.class,VehicleNotFoundException.class}) ResponseEntity<ApiErrorResponse> missing(Exception e,HttpServletRequest r){return out(HttpStatus.NOT_FOUND,e.getMessage(),r,List.of());}
 @ExceptionHandler(InvalidDriverAccountException.class) ResponseEntity<ApiErrorResponse> invalidAccount(Exception e,HttpServletRequest r){return out(HttpStatus.UNPROCESSABLE_ENTITY,e.getMessage(),r,List.of());}
 @ExceptionHandler(ForbiddenOperationException.class) ResponseEntity<ApiErrorResponse> forbidden(Exception e,HttpServletRequest r){return out(HttpStatus.FORBIDDEN,e.getMessage(),r,List.of());}
 @ExceptionHandler(DownstreamServiceException.class) ResponseEntity<ApiErrorResponse> downstream(Exception e,HttpServletRequest r){return out(HttpStatus.SERVICE_UNAVAILABLE,e.getMessage(),r,List.of());}
 @ExceptionHandler(Exception.class) ResponseEntity<ApiErrorResponse> unexpected(Exception e,HttpServletRequest r){return out(HttpStatus.INTERNAL_SERVER_ERROR,"An unexpected server error occurred",r,List.of());}
 private ResponseEntity<ApiErrorResponse> out(HttpStatus s,String m,HttpServletRequest r,List<ValidationError> v){return ResponseEntity.status(s).body(new ApiErrorResponse(Instant.now(),s.value(),s.getReasonPhrase(),m,r.getRequestURI(),v));}
}
