package lk.ac.sliit.ridelink.ride.presentation.controller;
import io.jsonwebtoken.Jwts; import io.jsonwebtoken.security.Keys; import lk.ac.sliit.ridelink.ride.application.dto.response.*; import lk.ac.sliit.ridelink.ride.application.port.out.*; import lk.ac.sliit.ridelink.ride.domain.enums.VehicleType; import org.junit.jupiter.api.Test; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.boot.test.mock.mockito.MockBean; import org.springframework.http.MediaType; import org.springframework.test.context.ActiveProfiles; import org.springframework.test.web.servlet.MockMvc; import java.math.BigDecimal; import java.nio.charset.StandardCharsets; import java.time.Instant; import java.util.*; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("test") class RideSecurityIntegrationTest {@Autowired MockMvc mvc;@MockBean AccountValidationPort accounts;@MockBean DriverAssignmentPort drivers;@MockBean FareCalculationPort fares;private static final String SECRET="test-only-secret-at-least-thirty-two-characters-long";
 @Test void missingTokenReturnsJson401()throws Exception{mvc.perform(post("/api/v1/rides").contentType(MediaType.APPLICATION_JSON).content("{}" )).andExpect(status().isUnauthorized()).andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON)).andExpect(jsonPath("$.status").value(401));}
 @Test void driverRoleCannotRequestRide()throws Exception{mvc.perform(post("/api/v1/rides").header("Authorization","Bearer "+token(UUID.randomUUID(),"DRIVER")).contentType(MediaType.APPLICATION_JSON).content(validRequest())).andExpect(status().isForbidden());}
 @Test void passengerCanRequestRide()throws Exception{UUID passenger=UUID.randomUUID(),profile=UUID.randomUUID();when(accounts.validate(passenger,"PASSENGER")).thenReturn(new AccountValidationData(passenger,"PASSENGER","ACTIVE",true));when(fares.estimate(any(),any())).thenReturn(new BigDecimal("1200"));when(drivers.eligible(any(),any())).thenReturn(List.of(new EligibleDriverData(profile,UUID.randomUUID(),UUID.randomUUID(),VehicleType.CAR,"Colombo",BigDecimal.ZERO,BigDecimal.ZERO,Instant.now())));mvc.perform(post("/api/v1/rides").header("Authorization","Bearer "+token(passenger,"PASSENGER")).contentType(MediaType.APPLICATION_JSON).content(validRequest())).andExpect(status().isCreated()).andExpect(jsonPath("$.status").value("ASSIGNED"));}
 private String validRequest(){return "{\"pickupName\":\"Fort\",\"destinationName\":\"Airport\",\"serviceArea\":\"Colombo\",\"simulatedDistanceKm\":10,\"vehicleType\":\"CAR\"}";}
 private String token(UUID subject,String role){Instant now=Instant.now();return Jwts.builder().subject(subject.toString()).issuer("ridelink-account-service").claim("role",role).claim("token_type","USER").issuedAt(Date.from(now)).expiration(Date.from(now.plusSeconds(300))).signWith(Keys.hmacShaKeyFor(SECRET.getBytes(StandardCharsets.UTF_8))).compact();}
}
