package lk.ac.sliit.ridelink.ride.application.usecase;
import lk.ac.sliit.ridelink.ride.application.dto.request.CreateRideRequest; import lk.ac.sliit.ridelink.ride.application.dto.response.*; import lk.ac.sliit.ridelink.ride.application.port.out.*; import lk.ac.sliit.ridelink.ride.domain.enums.*; import lk.ac.sliit.ridelink.ride.domain.exception.*; import lk.ac.sliit.ridelink.ride.domain.model.Ride; import lk.ac.sliit.ridelink.ride.domain.repository.RideRepository; import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension; import java.math.BigDecimal; import java.time.Instant; import java.util.*; import static org.junit.jupiter.api.Assertions.*; import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class) class RideApplicationServiceTest {@Mock RideRepository rides;@Mock AccountValidationPort accounts;@Mock DriverAssignmentPort drivers;@Mock FareCalculationPort fares;RideApplicationService service;UUID passenger=UUID.randomUUID(),driverAccount=UUID.randomUUID(),driverProfile=UUID.randomUUID(),vehicle=UUID.randomUUID();CreateRideRequest request=new CreateRideRequest("Fort","Airport","Colombo",new BigDecimal("25"),VehicleType.CAR);
 @BeforeEach void setup(){service=new RideApplicationService(rides,accounts,drivers,fares);lenient().when(accounts.validate(driverAccount,"DRIVER")).thenReturn(new AccountValidationData(driverAccount,"DRIVER","ACTIVE",true));}
 private EligibleDriverData candidate(Instant since,UUID profile){return new EligibleDriverData(profile,driverAccount,vehicle,VehicleType.CAR,"Colombo",BigDecimal.ZERO,BigDecimal.ZERO,since);}
 private void happyDependencies(){when(accounts.validate(passenger,"PASSENGER")).thenReturn(new AccountValidationData(passenger,"PASSENGER","ACTIVE",true));when(fares.estimate(VehicleType.CAR,new BigDecimal("25"))).thenReturn(new BigDecimal("2000"));lenient().when(drivers.eligible("Colombo",VehicleType.CAR)).thenReturn(List.of(candidate(Instant.parse("2025-01-01T00:00:00Z"),driverProfile)));when(rides.save(any())).thenAnswer(i->i.getArgument(0));}
 private Ride assigned(){Ride r=Ride.request(UUID.randomUUID(),passenger,"Fort","Airport","Colombo",new BigDecimal("25"),VehicleType.CAR,new BigDecimal("2000"));r.assign(driverAccount,driverProfile,vehicle);return r;}
 @Test void createsAndAssignsRide(){happyDependencies();RideResponse r=service.request(passenger,request);assertAll(()->assertEquals(RideStatus.ASSIGNED,r.status()),()->assertEquals(driverAccount,r.driverId()),()->assertEquals(new BigDecimal("2000"),r.estimatedFare()));verify(drivers).assign(eq(driverProfile),any());}
 @Test void rejectsInvalidPassenger(){when(accounts.validate(passenger,"PASSENGER")).thenReturn(new AccountValidationData(passenger,"DRIVER","ACTIVE",false));assertThrows(PassengerValidationException.class,()->service.request(passenger,request));verifyNoInteractions(fares,drivers,rides);}
 @Test void reportsNoDriver(){when(accounts.validate(passenger,"PASSENGER")).thenReturn(new AccountValidationData(passenger,"PASSENGER","ACTIVE",true));when(fares.estimate(any(),any())).thenReturn(BigDecimal.TEN);when(drivers.eligible(any(),any())).thenReturn(List.of());assertThrows(NoAvailableDriverException.class,()->service.request(passenger,request));}
 @Test void usesOldestDriverDeterministically(){happyDependencies();UUID older=UUID.randomUUID();when(drivers.eligible("Colombo",VehicleType.CAR)).thenReturn(List.of(candidate(Instant.parse("2025-02-01T00:00:00Z"),driverProfile),candidate(Instant.parse("2025-01-01T00:00:00Z"),older)));service.request(passenger,request);verify(drivers).assign(eq(older),any());}
 @Test void triesNextDriverAfterReservationConflict(){happyDependencies();UUID first=UUID.randomUUID();when(drivers.eligible(any(),any())).thenReturn(List.of(candidate(Instant.parse("2025-01-01T00:00:00Z"),first),candidate(Instant.parse("2025-02-01T00:00:00Z"),driverProfile)));doThrow(new DriverReservationConflictException("taken")).when(drivers).assign(eq(first),any());service.request(passenger,request);verify(drivers).assign(eq(driverProfile),any());}
 @Test void compensatesIfPersistenceFails(){happyDependencies();when(rides.save(any())).thenThrow(new RuntimeException("database down"));assertThrows(RuntimeException.class,()->service.request(passenger,request));verify(drivers).restore(eq(driverProfile),any());}
 @Test void acceptsAssignedRide(){Ride r=assigned();when(rides.findById(r.getId())).thenReturn(Optional.of(r));when(rides.save(r)).thenReturn(r);assertEquals(RideStatus.ACCEPTED,service.accept(r.getId(),driverAccount).status());}
 @Test void wrongDriverCannotAccept(){Ride r=assigned();UUID wrong=UUID.randomUUID();when(accounts.validate(wrong,"DRIVER")).thenReturn(new AccountValidationData(wrong,"DRIVER","ACTIVE",true));when(rides.findById(r.getId())).thenReturn(Optional.of(r));assertThrows(ForbiddenRideOperationException.class,()->service.accept(r.getId(),wrong));}
 @Test void completesAndRestoresDriver(){Ride r=assigned();r.accept(driverAccount);r.start(driverAccount);when(rides.findById(r.getId())).thenReturn(Optional.of(r));when(fares.finalFare(any(),any())).thenReturn(new BigDecimal("2300"));when(rides.save(any())).thenAnswer(i->i.getArgument(0));RideResponse out=service.complete(r.getId(),driverAccount);assertEquals(DriverSyncStatus.RELEASED,out.driverSyncStatus());verify(drivers).restore(driverProfile,r.getId());}
 @Test void retainsPendingReleaseWhenDriverUnavailable(){Ride r=assigned();r.accept(driverAccount);r.start(driverAccount);when(rides.findById(r.getId())).thenReturn(Optional.of(r));when(fares.finalFare(any(),any())).thenReturn(new BigDecimal("2300"));when(rides.save(any())).thenAnswer(i->i.getArgument(0));doThrow(new ExternalServiceException("down",false,null)).when(drivers).restore(driverProfile,r.getId());RideResponse out=service.complete(r.getId(),driverAccount);assertEquals(DriverSyncStatus.RELEASE_PENDING,out.driverSyncStatus());}
 @Test void passengerCanSeeOnlyOwnRide(){Ride r=assigned();when(rides.findById(r.getId())).thenReturn(Optional.of(r));assertThrows(ForbiddenRideOperationException.class,()->service.get(r.getId(),UUID.randomUUID(),"PASSENGER"));assertEquals(r.getId(),service.get(r.getId(),passenger,"PASSENGER").id());}
 @Test void missingRideReturnsNotFound(){UUID id=UUID.randomUUID();when(rides.findById(id)).thenReturn(Optional.empty());assertThrows(RideNotFoundException.class,()->service.accept(id,driverAccount));}
}
